### ISSUE TITLE
Patches is dying after about 5 minutes

### ISSUE THREAD

**Issue by bryanh1969** [dell/patches#26]
logs are attached.
[patches-backend_error.log](https://github.com/dell/patches/files/13241737/patches-backend_error.log)
[patches-backend_standard.log](https://github.com/dell/patches/files/13241738/patches-backend_standard.log)
[patches-frontend_error.log](https://github.com/dell/patches/files/13241739/patches-frontend_error.log)
[patches-frontend_standard.log](https://github.com/dell/patches/files/13241740/patches-frontend_standard.log)
[patches-httpd_error.log](https://github.com/dell/patches/files/13241741/patches-httpd_error.log)
[patches-httpd_standard.log](https://github.com/dell/patches/files/13241742/patches-httpd_standard.log)
[patches-nginx_error.log](https://github.com/dell/patches/files/13241743/patches-nginx_error.log)
[patches-nginx_standard.log](https://github.com/dell/patches/files/13241744/patches-nginx_standard.log)
[patches-psql_error.log](https://github.com/dell/patches/files/13241745/patches-psql_error.log)
[patches-psql_standard.log](https://github.com/dell/patches/files/13241746/patches-psql_standard.log)

**Comment by grantcurell** [comment]
These logs are empty. It looks like this system was turned on and then shutdown. Nothing to see here though?

Is this on the STIG'd version?

**Comment by grantcurell** [comment]
This occurs because recent STIGs broke how we were handling certs. I have addressed this.
