### ISSUE TITLE
Easy Install fails

### ISSUE THREAD

**Issue by bryanh1969** [dell/patches#29]
failing to find source code.

################################################################################
2024-01-02 13:25:09 - Running wget to grab Patches version v2.0.4...
################################################################################
--2024-01-02 13:25:09--  https://github.com/dell/patches/archive/refs/tags/v2.0.4.tar.gz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/dell/patches/tar.gz/refs/tags/v2.0.4 [following]
--2024-01-02 13:25:10--  https://codeload.github.com/dell/patches/tar.gz/refs/tags/v2.0.4
Resolving codeload.github.com (codeload.github.com)... 140.82.113.10
Connecting to codeload.github.com (codeload.github.com)|140.82.113.10|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-01-02 13:25:10 ERROR 404: Not Found.

################################################################################
2024-01-02 13:25:10 - Error: Failed to download the source code.
################################################################################

**Comment by grantcurell** [comment]
The tag was wrong. You can pull again. Here you could also have just changed the pulled tag to 2.04. The tag name was just missing a period.

**Comment by grantcurell** [comment]
(I have already fixed the tag though so no need to do it here)

**Comment by grantcurell** [comment]
Further clarification: you can use the same source code. The tag name was wrong on github.
